### ISSUE TITLE
sublime doesnt build atomic haxe

### ISSUE THREAD

**Issue by lewislepton** [rsredsq/atomic-haxe#4]
you know about this. but, im just making an issue just in case ;)
atom is fine though, its really slow in terms of it being atom ;)

**Comment by zhelezkov** [comment]
I just fresh installed a sublime text 3, then installed haxe package https://github.com/clemos/haxe-sublime-bundle. Build works fine for me. Autocompletion didn't work, I don't know why, maybe some issue in that package for sublime, because atom and flashdevelop works fine.

**Comment by lewislepton** [comment]
i was thinking of doing a clean install. but then just thinking that i should just stick with atom ;)

i will try though ;)
